services:
  ihatemoney:
    image: ihatemoney/ihatemoney:latest@sha256:5ff0b55411f5abb98539f571af56059608dff64f0dab8509f9ebddd8aacce4bd
    container_name: ihatemoney
    restart: unless-stopped
    environment:
      - SECRET_KEY=${IHATEMONEY_SECRET_KEY}
      - TZ=${TIMEZONE}
    volumes:
      - ihatemoney_data:/database
    networks:
      - proxy_net
    labels:
      - docker-volume-backup.stop-during-backup=ihatemoney

  backup:
    image: offen/docker-volume-backup:latest@sha256:26df48fdb7bd32f114fc7420beae3960055ae1f40ba5ff3bfd787cb5f15fefa5
    container_name: ihatemoney-backup
    restart: unless-stopped
    environment:
      - BACKUP_CRON_EXPRESSION=0 3 * * *
      - BACKUP_RETENTION_DAYS=30
      - BACKUP_FILENAME=ihatemoney-%Y-%m-%dT%H-%M-%S.tar.gz
      - BACKUP_ARCHIVE=/archive/ihatemoney
      - TZ=${TIMEZONE}
    volumes:
      - ihatemoney_data:/backup/ihatemoney_data:ro
      - nas_backup:/archive
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
    networks:
      - proxy_net

volumes:
  ihatemoney_data:
  nas_backup:
    driver: local
    driver_opts:
      type: cifs
      device: //${NAS_IP}/${NAS_BACKUP_SHARE}
      o: addr=${NAS_IP},username=${NAS_BACKUP_USER},password=${NAS_BACKUP_PASSWORD},file_mode=0700,dir_mode=0700

networks:
  proxy_net:
    external: true
